FROM mcr.microsoft.com/devcontainers/python:0-3.11
RUN pip install tensorflow==2.14
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN pip install gspread pandas datasets accelerate scikit-learn lxml transformers beautifulsoup4 tqdm ray tune scipy shap requests_oauthlib oauthlib matplotlib seaborn jupyter xformers